language: node_js
sudo: false
env:
  - CXX=g++-4.8
node_js:
  - "4.0"
  - "5.0"
before_script: "mv config/config.travis.js config/config.test.js"
services:
  - mongodb
  - redis-server
notifications:
  hipchat: 053fa30889406842ce2432d239b201@266484
  webhooks: http://desolate-woodland-3690.herokuapp.com/hubot/travis?room=ASQ
