sudo: required

language: node_js

services:
  - docker

before_install:
- docker pull redis
- docker run -d --name redis redis
- docker pull mongo
- docker run -d --name mongo mongo
- docker ps -a
- docker build -t asqhub/base-image:devel lib/support/docker/base-image/.
- docker build -t asqhub/asq_test:devel -f Dockerfile.test .

script:
# Overrides the init processes and runs the tests
- docker run -t --name asq --link mongo:mongo --link redis:redis asqhub/asq_test:devel npm test
#- docker run -d --name asq --link mongo:mongo --link redis:redis asqhub/asq_test:devel /sbin/my_init -- npm test

notifications:
  webhooks:
    urls:
      - $DOCKER_HUB_TRIGGER
    on_success: always
    on_failure: never
    on_start: never