sudo: required
dist: trusty
group: edge
language: bash
before_install:
- docker build -t asqhub/base-image:master lib/support/docker/base-image/.
- docker build -t $DOCKER_HUB_USERNAME/asq:test --build-arg CI_USER_TOKEN="${CI_USER_TOKEN}"
  -f Dockerfile.ci .
script:
- docker run -t --name asq $DOCKER_HUB_USERNAME/asq:test npm test
after_success:
- if [ "$TRAVIS_PULL_REQUEST" == "false" ] && ( [ "$TRAVIS_BRANCH" == "master" ] || [ "$TRAVIS_BRANCH" == "devel" ] || [ "$TRAVIS_BRANCH"
  =~ "^feat-*" ] ); then docker build -t $DOCKER_HUB_USERNAME/asq:$TRAVIS_BRANCH --build-arg
  CI_USER_TOKEN="${CI_USER_TOKEN}" -f Dockerfile .; docker login -u="$DOCKER_HUB_USERNAME" -p="$DOCKER_HUB_PASSWORD"; docker push $DOCKER_HUB_USERNAME/asq:$TRAVIS_BRANCH;
  fi
env:
  global:
  - secure: aelrJerHwLQtGsofEPs8Pds/wkeWLA+llpaPNk687zxpEpqxdt8GYgtYFVh1Md0KI/MDrTPyPIVxhBNNUCOwwfHzX/mXF8S/HokrKlfWaetpEDu8Wt9G/tyQjyxZxswqI/NV6Fn0Z/B+s6ONR+Ae7gJl7fCXLrzAoQSr76tR/bE=
  - secure: QcJBsy+HNvx5ZObDDn5yE9TNXM5IUmOLMnrTg6ejC/8MR8vPOq5svlQcL2539k28mZk3KoMm1CwT8Z0d/Mnm4PiFUxRMSR0WvK7xdcWVTQ9WLeMXD953uONCBjdZ4TPIXiC91VQS/jiigz9vLaT3G60tAOTnNWZvwaj11fns91g=
  - secure: Cba9Mexl0K6FfN/KZEbBaJ8wTd1DES0/5U+bixbWiNW6Yn6Zg4/9vvbGt20bFqdhVywldqzeB50/W8TjGRJ6naBD3OObYfQyUtCQphXAO41BEMGlemVkhmUkHI1Nu8Rcrc1/HHAClsObhVG4tycTXj00xmHT+NfEftpiPmGJChw=