#!/usr/bin/env node

// Download bower components that will be included with the pdf presentations
'use strict';

const fs = require('fs-extra');
const spawnSync = require('child_process').spawnSync;
const LiveAppSupportDir = 'lib/support/liveApp';
const bower_components = LiveAppSupportDir + '/bower_components'
const timeout = 120000; // 2 mins

function ifErrPrintAndExit(spawnPs){
  if(spawnPs.status > 0){
    process.stderr.write(spawnPs.stderr.toString() + '\n');
    process.exit(1);
  }
}
process.stdout.write('Deleting bower_components folder...');
fs.removeSync(bower_components);
process.stdout.write('done!\n');
// install bower deps
process.stdout.write('Installing bower dependencies for live app support...');
const out = spawnSync('bower',[
  'install',
  '--allow-root'
  ], {
  cwd: LiveAppSupportDir,
  timeout: timeout
});
ifErrPrintAndExit(out);
process.stdout.write('done!\n');
process.exit();
