#!/usr/bin/env node

'use strict';

var execSync = require('child_process').execSync;
var presenterControlDir = 'client/presenterControl';

process.stdout.write("Installing npm dependencies for PresenterControl...")
execSync("npm install --unsafe-perm", {
  cwd: presenterControlDir,
  timeout: 300000
});
process.stdout.write("done!\n")

process.stdout.write("Installing bower dependencies for PresenterControl...")
execSync("bower --allow-root install ", {
  cwd: presenterControlDir,
  timeout: 300000
});

process.stdout.write("done!")
process.exit();
