#!/usr/bin/env node

// Download, install and build ui-asq
'use strict';

const fs = require('fs');
const rimraf = require('rimraf');
const spawnSync = require('child_process').spawnSync;
const uiDir = 'public/ui';
const timeout = 300000; // 5 mins

function ifErrPrintAndExit(spawnPs){
  if(spawnPs.status > 0){
    process.stderr.write(spawnPs.stderr.toString() + '\n');
    process.exit(1);
  }
}

//clean
process.stdout.write('Cleaning ui-asq dir...');
rimraf.sync(uiDir);
process.stdout.write('done!\n');

// download
process.stdout.write('Downloading ui-asq...');
let out = spawnSync('git', [
  'clone',
  "https://" + process.env.CI_USER_TOKEN + ":x-oauth-basic@github.com/ASQ-USI/ui-asq",
   uiDir
  ],{
  timeout: timeout
});
ifErrPrintAndExit(out);
process.stdout.write('done!\n');

// install npm deps
process.stdout.write('Installing npm dependencies for ui-asq...');
out = spawnSync('npm', [
  'install',
  '--unsafe-perm'
  ], {
  cwd: uiDir,
  timeout: timeout
});
ifErrPrintAndExit(out);
process.stdout.write('done!\n');


// avoid using root .bowerrc by creating a local one
// with the default settings
process.stdout.write('Creating local .bowerrc...');
const bowerrcContents = `{
  "directory": "bower_components"
}`;
fs.writeFileSync(`${uiDir}/.bowerrc`, bowerrcContents);
process.stdout.write('done!\n');

// install bower deps
process.stdout.write('Installing bower dependencies for ui-asq...');
out = spawnSync('bower',[
  'install',
  '--allow-root'
  ], {
  cwd: uiDir,
  timeout: timeout
});
ifErrPrintAndExit(out);
process.stdout.write('done!\n');

// build
process.stdout.write('Building ui-asq...');
out = spawnSync('npm',[
  'run',
  'build'
  ], {
  cwd: uiDir,
  timeout: timeout
});
ifErrPrintAndExit(out);
process.stdout.write('done!\n');
process.exit();
